### ISSUE TITLE
RabbitMQ 3.6.2 RC1 - webmachine error /api/nodes

### ISSUE THREAD

**Issue by johnfoldager** [rabbitmq/rabbitmq-auth-backend-ldap#37] opened 2016-04-29 08:45 UTC
I see this in our logs:

```

=ERROR REPORT==== 29-Apr-2016::05:47:20 ===
webmachine error: path="/api/nodes"
{exit,{{{nocatch,{gen_tcp_error,enotconn}},
        [{eldap,send_the_LDAPMessage,3,[{file,"eldap.erl"},{line,991}]},
         {eldap,do_unbind,1,[{file,"eldap.erl"},{line,955}]},
         {eldap,loop,2,[{file,"eldap.erl"},{line,567}]}]},
       {gen_server2,call,
                    [<0.276.0>,
                     {submit,#Fun<rabbit_auth_backend_ldap.7.73774115>,
                             <0.7066.20>,reuse},
                     infinity]}},
      [{gen_server2,call,3,[{file,"src/gen_server2.erl"},{line,340}]},
       {rabbit_auth_backend_ldap,user_login_authentication,2,
                                 [{file,"src/rabbit_auth_backend_ldap.erl"},
                                  {line,64}]},
       {rabbit_access_control,try_authenticate,3,
                              [{file,"src/rabbit_access_control.erl"},
                               {line,91}]},
       {rabbit_access_control,'-check_user_login/2-fun-0-',4,
                              [{file,"src/rabbit_access_control.erl"},
                               {line,77}]},
       {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
       {rabbit_mgmt_util,is_authorized,6,
                         [{file,"src/rabbit_mgmt_util.erl"},{line,134}]},
       {webmachine_resource,resource_call,3,
                            [{file,"src/webmachine_resource.erl"},{line,186}]},
       {webmachine_resource,do,3,
                            [{file,"src/webmachine_resource.erl"},
                             {line,142}]}]}
```

**Comment by hairyhum** [comment] 2016-04-29 09:01
Duplicate of #36

**Closed as completed by hairyhum** 2016-04-29 09:01 UTC
Labels: duplicate
