### ISSUE TITLE
Is auth_ldap.dn_lookup_bind data type too limiting?

### ISSUE THREAD

**Issue by chuck2384** [rabbitmq/rabbitmq-auth-backend-ldap#113] opened 2019-10-01 15:51 UTC
You have the ability to specify a username and password, but then have an enum that wont allow it to be set:

```erlang
{mapping, "auth_ldap.dn_lookup_bind", "rabbitmq_auth_backend_ldap.dn_lookup_bind", [{datatype, [{enum, [as_user, anon]}]}]}
```

Also, I see no where that this would be breaking apart {user, password} and instead need to specify auth_ldap.dn_lookup_bind.user_dn and auth_ldap.dn_lookup_bind.password in the config. These work now but they are ignored with the case clause of dn_lookup_bind since you can only specify as_user or anon.

**Comment by lukebakken** [comment] 2019-10-01 16:06
Please see [this test case](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/89ca0893a7b0c05973fcbb638c6490b947284a08/test/config_schema_SUITE_data/rabbitmq_auth_backend_ldap.snippets#L119-L123), which demonstrates that the following does in fact work as intended:

```
auth_ldap.dn_lookup_bind.user_dn = username
auth_ldap.dn_lookup_bind.password = password
```

**Comment by michaelklishin** [comment] 2019-10-01 16:06
`auth_ldap.dn_lookup_bind` is a separate key from `auth_ldap.dn_lookup_bind.user_dn` and `auth_ldap.dn_lookup_bind.password`. The latter two exist because tuple types are not really a thing in the new style config format (Cuttlefish).

[This test case](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/test/config_schema_SUITE_data/rabbitmq_auth_backend_ldap.snippets#L119) seems to do what you want.

**Comment by chuck2384** [comment] 2019-10-01 17:00
Wouldn't [this case ](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/priv/schema/rabbitmq_auth_backend_ldap.schema#L133-L143 )ignore that since I'm unable to set anything besides as_user or anon?

This seems to be ignored in my case. I have the username and password set as above and still only users with LDAP access can authenticate; the bind doesn't seem to be working and its using as_user.

**Comment by lukebakken** [comment] 2019-10-01 17:02
@chuck2384 please use the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) to discuss this. When you post to the list, include the following information:

* RabbitMQ and Erlang version
* Operating system and version
* Complete configuration files. Obfuscate passwords if necessary
* Generated configuration files. These will be located in `/var/lib/rabbitmq/.../config/generated`

**Comment by michaelklishin** [comment] 2019-10-01 17:17
The translation function linked above will use `auth_ldap.dn_lookup_bind.user_dn` and `auth_ldap.dn_lookup_bind.password` if  `auth_ldap.dn_lookup_bind` is  anything other than `as_user` or `anon` and both credentials are set. Except for the `anon` clause, this has been the case for 3-4 years.

`rabbitmqctl environment` can be used to [verify effective configuration](https://www.rabbitmq.com/configure.html#verify-configuration-effective-configuration).

**Comment by chuck2384** [comment] 2019-10-01 17:22
@michaelklishin Thats exactly what I'm saying, you cant set `auth_ldap.dn_lookup_bind` to anything else.

I'll reply to the mailing list to discuss further

**Comment by chuck2384** [comment] 2019-10-01 17:46
you can see [here](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/rabbitmq-auth-backend-ldap-78/priv/schema/rabbitmq_auth_backend_ldap.schema#L127-128) this was previously set to string instead of the enum

**Comment by michaelklishin** [comment] 2019-10-02 03:46
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/JrDQeCnEDsU/discussion).

**Comment by michaelklishin** [comment] 2019-10-02 14:20
Closing according to the conclusion in the thread above.

**Closed as completed by michaelklishin** 2019-10-02 14:20 UTC
Labels: usability
